openapi: 3.0.3
info:
  title: Threat Processing API
  description: |-
    This API allows users to process a vulnerabilities file.
    They can export or import vulnerabilities in or outside the database.
  contact:
    email: apiteam@iut.io
  version: 0.1.0

servers:
  - url: http://127.0.0.1:5000/

tags:
  - name: Vulnerability
    description: Vulnerability Management

paths:
  /Vulnerability:
    get:
      tags:
        - Vulnerability
      summary: List vulnerabilities
      description: Retrieve all vulnerabilities
      responses:
        '200':
          description: Succès 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vulnerability'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vulnerability'
        '500':
          description: Erreur lors de la lecture du fichier JSON
    post:
      tags:
        - Vulnerability
      summary: Add a vulnerability
      description: Add a new vulnerability
      operationId: addVulnerability
      requestBody:
        description: Add a new vulnerability
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vulnerability'
          application/xml:
            schema:
              $ref: '#/components/schemas/Vulnerability'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vulnerability'
      responses:
        '200':
          description: Ajout Réussi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vulnerability'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vulnerability'
        '400':
          description: Données invalides ou champs manquants
        '422':
          description: L'ID existe déjà
          
    put:
      tags:
        - Vulnerability
      summary: Update vulnerability Auto
      description: Modify a specific vulnerability automatically
      operationId: updateVulnerabilityAuto
      responses:
        '200':
          description: Mise à jour réussie.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vulnerability'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vulnerability'
        '500':
          description: Erreur de lecture de la base de données 
        '404':
          description:  Aucune vulnérabilité avec cet ID

  /Vulnerability/{id}:
    get:
      tags:
        - Vulnerability
      summary: Find vulnerability by ID
      description: Retrieve a specific vulnerability by its ID
      operationId: getVulnerabilityById
      parameters:
        - name: id
          in: path
          description: ID of the vulnerability to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retourne la vulnérabilité correspondante
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vulnerability'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vulnerability'
        '404':
          description: Aucune vulnérabilité avec cet ID
        '500':
          description: Erreur de lecture de la base de données
    delete:
      tags:
        - Vulnerability
      summary: Delete vulnerability by ID
      description: Remove a vulnerability from the database
      operationId: deleteVulnerabilityById
      parameters:
        - name: id
          in: path
          description: ID of the vulnerability to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Suppression réussie 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vulnerability'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vulnerability'
        '500':
          description: Erreur de lecture de la base de données
        '404':
          description: Aucune vulnérabilité avec cet ID
    put:
      tags:
        - Vulnerability
      summary: Update vulnerability by ID
      description: Modify a specific vulnerability
      operationId: updateVulnerabilityById
      parameters:
        - name: id
          in: path
          description: ID of the vulnerability to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Mise à jour réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vulnerability'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vulnerability'
        '500':
          description:  Erreur de lecture de la base de données
        '404':
          description:  Aucune vulnérabilité avec cet ID
          
  /Vulnerability/sbom:
    post:
      tags:
        - Vulnerability
      summary: Process SBOM for report
      description: Processes SBOM to generate a report on vulnerabilities
      operationId: processSbomForReport
      responses:
        '200':
          description: Retourne les vulnérabilités correspondant au SBOM
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vulnerability'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vulnerability'
        '400':
          description: Clés manquantes dans l'entrée JSON
        '404':
          description: Aucune vulnérabilité correspondante trouvée 

  /Vulnerability/sbom/{id}:
    get:
      tags:
        - Vulnerability
      summary: Process SBOM for report by id
      description: Processes SBOM to generate a report on vulnerabilities
      operationId: processSbomForReportbyId
      parameters:
        - name: id
          in: path
          description: ID of the sbom database you want to test
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retourne les vulnérabilités associées au SBOM 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vulnerability'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vulnerability'
        '404':
          description: Aucune vulnérabilité correspondante trouvée
        '400':
          description: Clés manquantes dans les données récupérées
        '500':
          description: Erreur de lecture de la base de données
        '420':
          description: Erreur de liaison du microservice
          
components:
  schemas:
    Vulnerability:
      type: object
      properties:
        VulnerabilityID:
          type: string
        PkgName:
          type: string
        InstalledVersion:
          type: string
        FixedVersion:
          type: string
        Severity:
          type: string
        Title:
          type: string
        Description:
          type: string
        References:
          type: string
        id:
          type: integer