openapi: 3.0.3
info:
  title: API de Traitement des Menaces
  description: |-
    Cette API permet aux utilisateurs de traiter un fichier de vulnérabilités.
    Ils peuvent exporter ou importer des vulnérabilités dans ou hors de la base de données.
  contact:
    email: apiteam@iut.io
  version: 0.1.0

servers:
  - url: http://127.0.0.1:5000/

tags:
  - name: vulnerabilité
    description: Gestion des vulnérabilités

paths:
  /Vulnerability:
    get:
      tags:
        - vulnerabilité
      summary: Liste des vulnerabilités
      description: Récupérer toutes les vulnérabilités
      responses:
        '200':
          description: Succès 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/vulnerabilite'
        '500':
          description: Erreur lors de la lecture du fichier JSON
    post:
      tags:
        - vulnerabilité
      summary: Ajouter une vulnérabilité
      description: Ajouter une vulnérabilité
      operationId: AjouterVulnerabilite
      requestBody:
        description: Ajouter une nouvelle vulnérabilité
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vulnerabilite'
          application/xml:
            schema:
              $ref: '#/components/schemas/vulnerabilite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/vulnerabilite'
      responses:
        '200':
          description: Ajout Réussi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
        '400':
          description: Données invalides ou champs manquants
        '422':
          description: L'ID existe déjà
          
    put:
      tags:
        - vulnerabilité
      summary: Mise à jour automatique de la vulnérabilité
      description: Modifier automatiquement une vulnérabilité spécifique
      operationId: MiseAJourParID
      responses:
        '200':
          description: Mise à jour réussie.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
        '500':
          description: Erreur de lecture de la base de données 
        '404':
          description:  Aucune vulnérabilité avec cet ID

  /Vulnerability/{id}:
    get:
      tags:
        - vulnerabilité
      summary: Trouver une vulnérabilité par ID
      description: Trouver une vulnérabilité spécifique par ID
      operationId: VulnerabiliteParID
      parameters:
        - name: id
          in: path
          description: ID de la vulnerabilité a affiché
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retourne la vulnérabilité correspondante
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
        '404':
          description: Aucune vulnérabilité avec cet ID
        '500':
          description: Erreur de lecture de la base de données
    delete:
      tags:
        - vulnerabilité
      summary: Supprimer une vulnérabilité par ID
      description: Supprimer une vulnérabilité de la base de données
      operationId: SupprimerParID
      parameters:
        - name: id
          in: path
          description: ID de la vulnérabilité a supprimer
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Suppression réussie 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
        '500':
          description: Erreur de lecture de la base de données
        '404':
          description: Aucune vulnérabilité avec cet ID
    put:
      tags:
        - vulnerabilité
      summary: Mise-à-jour d'une vulnérabilité par ID
      description: Modifier une vulnérabilité
      operationId: MiseAjourParID
      parameters:
        - name: id
          in: path
          description: ID de la vulnérabilité à mettre à jour
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Mise à jour réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
        '500':
          description:  Erreur de lecture de la base de données
        '404':
          description:  Aucune vulnérabilité avec cet ID
          
  /Vulnerability/sbom:
    post:
      tags:
        - vulnerabilité
      summary: Traiter le SBOM pour le rapport
      description: Traite le SBOM pour générer un rapport sur les vulnérabilités
      operationId: TraitementSBOM
      responses:
        '200':
          description: Retourne les vulnérabilités correspondant au SBOM
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
        '400':
          description: Clés manquantes dans l'entrée JSON
        '404':
          description: Aucune vulnérabilité correspondante trouvée 

  /Vulnerability/sbom/{id}:
    get:
      tags:
        - vulnerabilité
      summary: Traiter le SBOM pour générer un rapport par ID
      description: Traite le SBOM pour générer un rapport sur les vulnérabilités
      operationId: TraiterSBOMParProjet
      parameters:
        - name: id
          in: path
          description: ID du sbom a tester
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retourne les vulnérabilités associées au SBOM 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
        '404':
          description: Aucune vulnérabilité correspondante trouvée
        '400':
          description: Clés manquantes dans les données récupérées
        '500':
          description: Erreur de lecture de la base de données
        '420':
          description: Erreur de liaison du microservice
          
  /Vulnerability/sbom/CVE:
    post:
      tags:
        - vulnerabilité
      summary: Traiter le SBOM grâce a l'API CVE
      description: Traite le SBOM pour générer un rapport sur les vulnérabilités
      operationId: TraiteSBOMParAPI
      responses:
        '200':
          description: Retourne les vulnérabilités associées au SBOM 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
            application/xml:
              schema:
                $ref: '#/components/schemas/vulnerabilite'
        '404':
          description: Aucune vulnérabilité correspondante trouvée
        '400':
          description: Clés manquantes dans les données récupérées
        '505':
          description: Erreur lors de la requête CVE

components:
  schemas:
    vulnerabilite:
      type: object
      properties:
        VulnerabilityID:
          type: string
        PkgName:
          type: string
        InstalledVersion:
          type: string
        FixedVersion:
          type: string
        Severity:
          type: string
        Title:
          type: string
        Description:
          type: string
        References:
          type: string
        id:
          type: integer
