openapi: 3.0.3
info:
  title: API de gestion des projets
  description: |-
    Affiche les différents projets ainsi que les détails les concernants.
  contact:
    email: paul.hoffbeck@etudiant.univ-rennes.fr
  version: 0.1.0
servers:
  - url: https://librairie.rt.lan/api/v1
tags:
  - name: projets
    description: Gestion des projets
  - name: user
    description: Operations about user
paths:
  /projet:
    get:
      tags:
        - projets
      summary: Lister les projets
      description: Afficher tous les projets
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Projet'          
        '400':
          description: Invalid status value
          
          
    post:
      tags:
        - projets
      summary: Ajouter un projet
      description: Ajouter un projet à la liste des projets
      requestBody:
        description: Ajouter un projet
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Projet'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Projet'          
        '400':
          description: Invalid input
        '422':
          description: Validation exception
          
          
          
  /projet/{projetId}:
    get:
      tags:
        - projets
      summary: Recherche de projets par identifiant
      description: Retourne un projet
      operationId: getBookById
      parameters:
        - name: projetId
          in: path
          description: ID du projet à rechercher
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Projet'          
        '400':
          description: Invalid ID supplied

          
  /projet/cherche/sbom/{projetId}:
    get:
      tags:
      - projets
      parameters:
        - name: projetId
          in: path
          description: ID du projet à rechercher
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
          
  /projet/cherche/vulne/{projetId}:
    get:
      tags:
      - projets
      parameters:
        - name: projetId
          in: path
          description: ID du projet à rechercher
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
          
  /projet/cherche/rapport/{projetId}:
    get:
      tags:
      - projets
      parameters:
        - name: projetId
          in: path
          description: ID du projet à rechercher
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied

components:
  schemas:
    Projet:
      type: object
      properties:
        id:
          type: integer
        nom:
          type: string
        description:
          type: string
        sbom:
          type: string
        vulne:
          type: string
        rapport:
          type: object
        utilisateurs:
          type: string
    
    User:
      type: object
      properties:
        nom:
          type: string
        prenom:
          type: string
        email:
          type: string
        password:
          type: string
        naissance:
          type: string
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          